##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: portworx-io-priority-high
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "1"
   snap_interval:   "70"

---

##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: pvcsc001
   annotations:
     volume.beta.kubernetes.io/storage-class: portworx-io-priority-high
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi

---

##### Pod using a volume dynamically provisioned from above volume claim
apiVersion: v1
kind: Pod
metadata:
   name: nginx
spec:
   containers:
   - name: nginx
     image: nginx
     volumeMounts:
     - name: test-volume
       mountPath: /mnt
   volumes:
   - name: test-volume
     persistentVolumeClaim:
       claimName: <pvc-name>