kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  # format is name.<new_volume_name>-source.<old_pvc_pxsnap_name>
  name: name.snap001-source.pvcsc001
  annotations:
    volume.beta.kubernetes.io/storage-class: portworx-io-priority-high
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi
