##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: portworx-io-priority-high
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "1"
   snap_interval:   "70"
   io_priority:  "high"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  # format is name.<new_volume_name>-source.<old_volume_name>
  name: name.snap001-source.pvcsc001
  annotations:
    volume.beta.kubernetes.io/storage-class: portworx-io-priority-high
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi
